stages: [ build ]

format-xml:
  image: ubuntu:15.10
  stage: build
  script:
    - echo "deb http://se.archive.ubuntu.com/ubuntu/ trusty multiverse" >> /etc/apt/sources.list
    - export http_proxy=http://proxy.int.dev.terastrm.net:8888/
    - export https_proxy=http://proxy.int.dev.terastrm.net:8888/
    - apt-get update && apt-get install -y xml2rfc
    - xml2rfc draft-kowalewski-netmod-supplemental-common-yang-data-types.xml draft-kowalewski-netmod-supplemental-common-yang-data-types-00.html
    - xml2rfc draft-kowalewski-netmod-supplemental-common-yang-data-types.xml draft-kowalewski-netmod-supplemental-common-yang-data-types-00.txt
