stages: [ build ]

format-xml:
  image: repo.dev.terastrm.net:5000/ts-ubuntu-xml2rfc:latest
  stage: build
  artifacts:
    paths:
      - draft-kowalewski-netmod-supplemental-common-yang-data-types-00.html
      - draft-kowalewski-netmod-supplemental-common-yang-data-types-00.txt
  script:
    - xml2rfc draft-kowalewski-netmod-supplemental-common-yang-data-types.xml draft-kowalewski-netmod-supplemental-common-yang-data-types-00.html
    - xml2rfc draft-kowalewski-netmod-supplemental-common-yang-data-types.xml draft-kowalewski-netmod-supplemental-common-yang-data-types-00.txt
